### ISSUE TITLE
qbcore?

### ISSUE THREAD

**Issue by ghost** [NoLagJustHex/SimpleDispatch-Command-based-#1]
Maybe make it Standalone so you can choose from esx and qbcore?

**Comment by NoLagJustHex** [comment]
Hey, thanks for your suggestion. But as far as I know, this is nearly impossible since there is no FiveM-Native for giving specific players money in the [FiveM-Native-Reference](https://docs.fivem.net/natives/). I'm currently working on a QBCore Version, but somehow I don't get it working.

Regards
pronince
